import json, os

locales = ['ar', 'en', 'fr', 'tr', 'pt', 'es', 'de']
translations = {
    'ar': {
        'title': 'جدول المحطة - إيجون إير',
        'day_0': 'الأحد',
        'day_1': 'الإثنين',
        'day_2': 'الثلاثاء',
        'day_3': 'الأربعاء',
        'day_4': 'الخميس',
        'day_5': 'الجمعة',
        'day_6': 'السبت',
        'recurrence_DAILY': 'يومي',
        'recurrence_WEEKLY': 'أسبوعي',
        'recurrence_SELECTED_DAYS': 'أيام مختارة',
        'recurrence_ONE_TIME': 'مرة واحدة',
        'managerDefaultName': 'مدير المحطة',
        'pageTitle': 'جدول المحطة الأسبوعي',
        'programsButton': '⚙️ البرامج',
        'backToDashboard': '← اللوحة',
        'allStations': 'كل المحطات',
        'summary': '📺 {count} برنامج · الأسبوع الحالي (يبدأ من السبت)',
        'noProgramsTitle': 'لا توجد برامج مجدولة',
        'noProgramsDesc': 'أضف جدولاً للبرامج من صفحة إدارة البرامج.',
        'manageProgramsBtn': '⚙️ إدارة البرامج',
        'today': 'اليوم',
        'noBroadcast': 'لا يوجد بث مجدول.',
        'editProgram': 'تعديل البرنامج →',
        'noStationsAssigned': 'لا توجد محطات مسندة',
        'noStationsAssignedDesc': 'تواصل مع الإدارة لتفعيل المحطات المرتبطة بحسابك.',
        'backToDashboardAction': '← العودة للوحة'
    },
    'en': {
        'title': 'Station Schedule - EGONAIR',
        'day_0': 'Sunday',
        'day_1': 'Monday',
        'day_2': 'Tuesday',
        'day_3': 'Wednesday',
        'day_4': 'Thursday',
        'day_5': 'Friday',
        'day_6': 'Saturday',
        'recurrence_DAILY': 'Daily',
        'recurrence_WEEKLY': 'Weekly',
        'recurrence_SELECTED_DAYS': 'Selected Days',
        'recurrence_ONE_TIME': 'One Time',
        'managerDefaultName': 'Station Manager',
        'pageTitle': 'Weekly Station Schedule',
        'programsButton': '⚙️ Programs',
        'backToDashboard': '← Dashboard',
        'allStations': 'All Stations',
        'summary': '📺 {count} Programs · Current week (Starts Saturday)',
        'noProgramsTitle': 'No scheduled programs',
        'noProgramsDesc': 'Add a program schedule from the program management page.',
        'manageProgramsBtn': '⚙️ Manage Programs',
        'today': 'Today',
        'noBroadcast': 'No broadcast scheduled.',
        'editProgram': 'Edit Program →',
        'noStationsAssigned': 'No assigned stations',
        'noStationsAssignedDesc': 'Contact administration to activate stations linked to your account.',
        'backToDashboardAction': '← Back to Dashboard'
    },
    'fr': {
        'title': 'Grille de la Station - EGONAIR',
        'day_0': 'Dimanche',
        'day_1': 'Lundi',
        'day_2': 'Mardi',
        'day_3': 'Mercredi',
        'day_4': 'Jeudi',
        'day_5': 'Vendredi',
        'day_6': 'Samedi',
        'recurrence_DAILY': 'Quotidien',
        'recurrence_WEEKLY': 'Hebdomadaire',
        'recurrence_SELECTED_DAYS': 'Jours Sélectionnés',
        'recurrence_ONE_TIME': 'Une Fois',
        'managerDefaultName': 'Manager de Station',
        'pageTitle': 'Grille Hebdomadaire de la Station',
        'programsButton': '⚙️ Programmes',
        'backToDashboard': '← Tableau de Bord',
        'allStations': 'Toutes les Stations',
        'summary': '📺 {count} Programmes · Semaine en cours (Débute Samedi)',
        'noProgramsTitle': 'Aucun programme prévu',
        'noProgramsDesc': 'Ajoutez un programme depuis la page de gestion des programmes.',
        'manageProgramsBtn': '⚙️ Gérer les Programmes',
        'today': 'Aujourd\'hui',
        'noBroadcast': 'Aucune diffusion prévue.',
        'editProgram': 'Modifier le Programme →',
        'noStationsAssigned': 'Aucune station attribuée',
        'noStationsAssignedDesc': 'Contactez l\'administration pour activer les stations liées à votre compte.',
        'backToDashboardAction': '← Retour au Tableau de Bord'
    },
    'tr': {
        'title': 'İstasyon Programı - EGONAIR',
        'day_0': 'Pazar',
        'day_1': 'Pazartesi',
        'day_2': 'Salı',
        'day_3': 'Çarşamba',
        'day_4': 'Perşembe',
        'day_5': 'Cuma',
        'day_6': 'Cumartesi',
        'recurrence_DAILY': 'Günlük',
        'recurrence_WEEKLY': 'Haftalık',
        'recurrence_SELECTED_DAYS': 'Seçili Günler',
        'recurrence_ONE_TIME': 'Bir Kere',
        'managerDefaultName': 'İstasyon Yöneticisi',
        'pageTitle': 'Haftalık İstasyon Programı',
        'programsButton': '⚙️ Programlar',
        'backToDashboard': '← Pano',
        'allStations': 'Tüm İstasyonlar',
        'summary': '📺 {count} Program · Mevcut hafta (Cumartesi başlar)',
        'noProgramsTitle': 'Planlanmış program yok',
        'noProgramsDesc': 'Program yönetimi sayfasından bir program ekleyin.',
        'manageProgramsBtn': '⚙️ Programları Yönet',
        'today': 'Bugün',
        'noBroadcast': 'Planlanmış yayın yok.',
        'editProgram': 'Programı Düzenle →',
        'noStationsAssigned': 'Atanmış istasyon yok',
        'noStationsAssignedDesc': 'Hesabınıza bağlı istasyonları etkinleştirmek için yönetimle iletişime geçin.',
        'backToDashboardAction': '← Panoya Dön'
    },
    'pt': {
        'title': 'Programação da Estação - EGONAIR',
        'day_0': 'Domingo',
        'day_1': 'Segunda-feira',
        'day_2': 'Terça-feira',
        'day_3': 'Quarta-feira',
        'day_4': 'Quinta-feira',
        'day_5': 'Sexta-feira',
        'day_6': 'Sábado',
        'recurrence_DAILY': 'Diário',
        'recurrence_WEEKLY': 'Semanal',
        'recurrence_SELECTED_DAYS': 'Dias Selecionados',
        'recurrence_ONE_TIME': 'Uma Vez',
        'managerDefaultName': 'Gerente de Estação',
        'pageTitle': 'Programação Semanal da Estação',
        'programsButton': '⚙️ Programas',
        'backToDashboard': '← Painel',
        'allStations': 'Todas as Estações',
        'summary': '📺 {count} Programas · Semana atual (Começa Sábado)',
        'noProgramsTitle': 'Nenhum programa agendado',
        'noProgramsDesc': 'Adicione um programa na página de gerenciamento de programas.',
        'manageProgramsBtn': '⚙️ Gerenciar Programas',
        'today': 'Hoje',
        'noBroadcast': 'Nenhuma transmissão agendada.',
        'editProgram': 'Editar Programa →',
        'noStationsAssigned': 'Nenhuma estação atribuída',
        'noStationsAssignedDesc': 'Contate a administração para ativar as estações vinculadas à sua conta.',
        'backToDashboardAction': '← Voltar ao Painel'
    },
    'es': {
        'title': 'Horario de la Estación - EGONAIR',
        'day_0': 'Domingo',
        'day_1': 'Lunes',
        'day_2': 'Martes',
        'day_3': 'Miércoles',
        'day_4': 'Jueves',
        'day_5': 'Viernes',
        'day_6': 'Sábado',
        'recurrence_DAILY': 'Diario',
        'recurrence_WEEKLY': 'Semanal',
        'recurrence_SELECTED_DAYS': 'Días Seleccionados',
        'recurrence_ONE_TIME': 'Una Vez',
        'managerDefaultName': 'Gerente de Estación',
        'pageTitle': 'Horario Semanal de la Estación',
        'programsButton': '⚙️ Programas',
        'backToDashboard': '← Panel',
        'allStations': 'Todas las Estaciones',
        'summary': '📺 {count} Programas · Semana actual (Empieza el Sábado)',
        'noProgramsTitle': 'No hay programas programados',
        'noProgramsDesc': 'Añade un horario desde la página de gestión de programas.',
        'manageProgramsBtn': '⚙️ Gestionar Programas',
        'today': 'Hoy',
        'noBroadcast': 'No hay transmisión programada.',
        'editProgram': 'Editar Programa →',
        'noStationsAssigned': 'No hay estaciones asignadas',
        'noStationsAssignedDesc': 'Contacta a administración para activar las estaciones en tu cuenta.',
        'backToDashboardAction': '← Volver al Panel'
    },
    'de': {
        'title': 'Sendeplan - EGONAIR',
        'day_0': 'Sonntag',
        'day_1': 'Montag',
        'day_2': 'Dienstag',
        'day_3': 'Mittwoch',
        'day_4': 'Donnerstag',
        'day_5': 'Freitag',
        'day_6': 'Samstag',
        'recurrence_DAILY': 'Täglich',
        'recurrence_WEEKLY': 'Wöchentlich',
        'recurrence_SELECTED_DAYS': 'Ausgewählte Tage',
        'recurrence_ONE_TIME': 'Einmalig',
        'managerDefaultName': 'Stationsmanager',
        'pageTitle': 'Wöchentlicher Sendeplan',
        'programsButton': '⚙️ Programme',
        'backToDashboard': '← Dashboard',
        'allStations': 'Alle Stationen',
        'summary': '📺 {count} Programme · Aktuelle Woche (Startet Samstag)',
        'noProgramsTitle': 'Keine Programme geplant',
        'noProgramsDesc': 'Fügen Sie einen Programmplan über die Programmverwaltungsseite hinzu.',
        'manageProgramsBtn': '⚙️ Programme Verwalten',
        'today': 'Heute',
        'noBroadcast': 'Keine Sendung geplant.',
        'editProgram': 'Programm Bearbeiten →',
        'noStationsAssigned': 'Keine Stationen zugewiesen',
        'noStationsAssignedDesc': 'Kontaktieren Sie die Verwaltung, um Stationen zu aktivieren.',
        'backToDashboardAction': '← Zurück zum Dashboard'
    }
}

base_path = 'frontend/messages'

for lang in locales:
    file_path = os.path.join(base_path, f'{lang}.json')
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        if 'stationManager' not in data:
            data['stationManager'] = {}
            
        data['stationManager']['schedule'] = translations[lang]

        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write('\n')

print("Translations patched for stationManager.schedule!")
