import json, os

locales = ['ar', 'en', 'fr', 'tr', 'pt', 'es', 'de']
translations = {
    'ar': {
        'title': 'لوحة مدير المحطة',
        'subtitle': 'EGONAIR',
        'hello': 'مرحباً،',
        'profile': 'ملفي',
        'logout': 'خروج',
        'logoutFull': 'تسجيل الخروج',
        'welcome': 'مرحباً، {name} 👋',
        'welcomeDesc': 'تعرض هذه اللوحة المحطات المسندة إليك فقط. لا يمكنك الوصول إلى بيانات المحطات الأخرى أو لوحة الإدارة العامة.',
        'assignedStations': 'المحطات المُسندة',
        'totalPresenters': 'إجمالي المذيعين',
        'totalPrograms': 'إجمالي البرامج',
        'totalRecordings': 'إجمالي التسجيلات',
        'fetchError': 'حدث خطأ أثناء تحميل البيانات. حاول تحديث الصفحة.',
        'noStationsTitle': 'لا توجد محطات مسندة لهذا الحساب',
        'noStationsDesc': 'تواصل مع الإدارة لتفعيل المحطات المرتبطة بحسابك.',
        'yourAssignedStations': 'محطاتك المُسندة',
        'active': 'نشطة',
        'inactive': 'معطّلة',
        'djCredsSet': 'بيانات DJ الافتراضية مُعدة',
        'djCredsNotSet': 'بيانات DJ الافتراضية غير مُعدة',
        'presenters': 'المذيعون',
        'programs': 'البرامج',
        'recordings': 'التسجيلات',
        'actions': 'الإجراءات',
        'actionPresenters': 'مذيعو المحطة',
        'actionPrograms': 'برامج المحطة',
        'actionRecordings': 'تسجيلات المحطة',
        'actionDj': 'إعدادات DJ',
        'actionMedia': 'مكتبة الوسائط',
        'actionSchedule': 'جدول المحطة',
        'open': 'فتح',
        'comingSoon': 'قريبًا'
    },
    'en': {
        'title': 'Station Manager Dashboard',
        'subtitle': 'EGONAIR',
        'hello': 'Hello,',
        'profile': 'My Profile',
        'logout': 'Logout',
        'logoutFull': 'Logout',
        'welcome': 'Hello, {name} 👋',
        'welcomeDesc': 'This dashboard only shows stations assigned to you. You cannot access other stations or the main admin panel.',
        'assignedStations': 'Assigned Stations',
        'totalPresenters': 'Total Presenters',
        'totalPrograms': 'Total Programs',
        'totalRecordings': 'Total Recordings',
        'fetchError': 'An error occurred while loading data. Please try refreshing the page.',
        'noStationsTitle': 'No stations assigned to this account',
        'noStationsDesc': 'Contact the administration to activate stations for your account.',
        'yourAssignedStations': 'Your Assigned Stations',
        'active': 'Active',
        'inactive': 'Inactive',
        'djCredsSet': 'Default DJ Credentials Set',
        'djCredsNotSet': 'Default DJ Credentials Not Set',
        'presenters': 'Presenters',
        'programs': 'Programs',
        'recordings': 'Recordings',
        'actions': 'Actions',
        'actionPresenters': 'Station Presenters',
        'actionPrograms': 'Station Programs',
        'actionRecordings': 'Station Recordings',
        'actionDj': 'DJ Settings',
        'actionMedia': 'Media Library',
        'actionSchedule': 'Station Schedule',
        'open': 'Open',
        'comingSoon': 'Coming Soon'
    },
    'fr': {
        'title': 'Tableau de Bord du Gestionnaire',
        'subtitle': 'EGONAIR',
        'hello': 'Bonjour,',
        'profile': 'Mon Profil',
        'logout': 'Déconnexion',
        'logoutFull': 'Se Déconnecter',
        'welcome': 'Bonjour, {name} 👋',
        'welcomeDesc': 'Ce tableau de bord ne montre que les stations qui vous sont attribuées. Vous ne pouvez pas accéder à d\'autres stations ou au panneau d\'administration principal.',
        'assignedStations': 'Stations Attribuées',
        'totalPresenters': 'Total des Présentateurs',
        'totalPrograms': 'Total des Programmes',
        'totalRecordings': 'Total des Enregistrements',
        'fetchError': 'Une erreur s\'est produite lors du chargement des données. Veuillez rafraîchir la page.',
        'noStationsTitle': 'Aucune station attribuée à ce compte',
        'noStationsDesc': 'Contactez l\'administration pour activer des stations pour votre compte.',
        'yourAssignedStations': 'Vos Stations Attribuées',
        'active': 'Actif',
        'inactive': 'Inactif',
        'djCredsSet': 'Identifiants DJ par défaut définis',
        'djCredsNotSet': 'Identifiants DJ par défaut non définis',
        'presenters': 'Présentateurs',
        'programs': 'Programmes',
        'recordings': 'Enregistrements',
        'actions': 'Actions',
        'actionPresenters': 'Présentateurs de la Station',
        'actionPrograms': 'Programmes de la Station',
        'actionRecordings': 'Enregistrements de la Station',
        'actionDj': 'Paramètres DJ',
        'actionMedia': 'Médiathèque',
        'actionSchedule': 'Programme de la Station',
        'open': 'Ouvrir',
        'comingSoon': 'Bientôt'
    },
    'tr': {
        'title': 'İstasyon Yöneticisi Panosu',
        'subtitle': 'EGONAIR',
        'hello': 'Merhaba,',
        'profile': 'Profilim',
        'logout': 'Çıkış Yap',
        'logoutFull': 'Çıkış Yap',
        'welcome': 'Merhaba, {name} 👋',
        'welcomeDesc': 'Bu pano yalnızca size atanan istasyonları gösterir. Diğer istasyonlara veya ana yönetici paneline erişemezsiniz.',
        'assignedStations': 'Atanan İstasyonlar',
        'totalPresenters': 'Toplam Sunucular',
        'totalPrograms': 'Toplam Programlar',
        'totalRecordings': 'Toplam Kayıtlar',
        'fetchError': 'Veriler yüklenirken bir hata oluştu. Lütfen sayfayı yenilemeyi deneyin.',
        'noStationsTitle': 'Bu hesaba atanmış istasyon yok',
        'noStationsDesc': 'Hesabınız için istasyonları etkinleştirmek üzere yönetimle iletişime geçin.',
        'yourAssignedStations': 'Atanan İstasyonlarınız',
        'active': 'Aktif',
        'inactive': 'Pasif',
        'djCredsSet': 'Varsayılan DJ Kimlik Bilgileri Ayarlandı',
        'djCredsNotSet': 'Varsayılan DJ Kimlik Bilgileri Ayarlanmadı',
        'presenters': 'Sunucular',
        'programs': 'Programlar',
        'recordings': 'Kayıtlar',
        'actions': 'İşlemler',
        'actionPresenters': 'İstasyon Sunucuları',
        'actionPrograms': 'İstasyon Programları',
        'actionRecordings': 'İstasyon Kayıtları',
        'actionDj': 'DJ Ayarları',
        'actionMedia': 'Medya Kütüphanesi',
        'actionSchedule': 'İstasyon Yayın Akışı',
        'open': 'Aç',
        'comingSoon': 'Yakında'
    },
    'pt': {
        'title': 'Painel do Gerente da Estação',
        'subtitle': 'EGONAIR',
        'hello': 'Olá,',
        'profile': 'Meu Perfil',
        'logout': 'Sair',
        'logoutFull': 'Sair da Conta',
        'welcome': 'Olá, {name} 👋',
        'welcomeDesc': 'Este painel mostra apenas as estações atribuídas a você. Você não pode acessar outras estações ou o painel de administração principal.',
        'assignedStations': 'Estações Atribuídas',
        'totalPresenters': 'Total de Apresentadores',
        'totalPrograms': 'Total de Programas',
        'totalRecordings': 'Total de Gravações',
        'fetchError': 'Ocorreu um erro ao carregar os dados. Por favor, tente atualizar a página.',
        'noStationsTitle': 'Nenhuma estação atribuída a esta conta',
        'noStationsDesc': 'Entre em contato com a administração para ativar estações para sua conta.',
        'yourAssignedStations': 'Suas Estações Atribuídas',
        'active': 'Ativo',
        'inactive': 'Inativo',
        'djCredsSet': 'Credenciais DJ Padrão Definidas',
        'djCredsNotSet': 'Credenciais DJ Padrão Não Definidas',
        'presenters': 'Apresentadores',
        'programs': 'Programas',
        'recordings': 'Gravações',
        'actions': 'Ações',
        'actionPresenters': 'Apresentadores da Estação',
        'actionPrograms': 'Programas da Estação',
        'actionRecordings': 'Gravações da Estação',
        'actionDj': 'Configurações DJ',
        'actionMedia': 'Biblioteca de Mídia',
        'actionSchedule': 'Programação da Estação',
        'open': 'Abrir',
        'comingSoon': 'Em breve'
    },
    'es': {
        'title': 'Panel del Gerente de Estación',
        'subtitle': 'EGONAIR',
        'hello': 'Hola,',
        'profile': 'Mi Perfil',
        'logout': 'Cerrar Sesión',
        'logoutFull': 'Cerrar Sesión',
        'welcome': 'Hola, {name} 👋',
        'welcomeDesc': 'Este panel solo muestra las estaciones asignadas a ti. No puedes acceder a otras estaciones ni al panel de administración principal.',
        'assignedStations': 'Estaciones Asignadas',
        'totalPresenters': 'Total de Presentadores',
        'totalPrograms': 'Total de Programas',
        'totalRecordings': 'Total de Grabaciones',
        'fetchError': 'Ocurrió un error al cargar los datos. Por favor, intenta actualizar la página.',
        'noStationsTitle': 'No hay estaciones asignadas a esta cuenta',
        'noStationsDesc': 'Contacta con la administración para activar estaciones para tu cuenta.',
        'yourAssignedStations': 'Tus Estaciones Asignadas',
        'active': 'Activo',
        'inactive': 'Inactivo',
        'djCredsSet': 'Credenciales DJ Predeterminadas Configuradas',
        'djCredsNotSet': 'Credenciales DJ Predeterminadas No Configuradas',
        'presenters': 'Presentadores',
        'programs': 'Programas',
        'recordings': 'Grabaciones',
        'actions': 'Acciones',
        'actionPresenters': 'Presentadores de la Estación',
        'actionPrograms': 'Programas de la Estación',
        'actionRecordings': 'Grabaciones de la Estación',
        'actionDj': 'Configuraciones DJ',
        'actionMedia': 'Biblioteca de Medios',
        'actionSchedule': 'Programación de la Estación',
        'open': 'Abrir',
        'comingSoon': 'Próximamente'
    },
    'de': {
        'title': 'Stationsmanager-Dashboard',
        'subtitle': 'EGONAIR',
        'hello': 'Hallo,',
        'profile': 'Mein Profil',
        'logout': 'Abmelden',
        'logoutFull': 'Ausloggen',
        'welcome': 'Hallo, {name} 👋',
        'welcomeDesc': 'Dieses Dashboard zeigt nur die Ihnen zugewiesenen Stationen an. Sie können nicht auf andere Stationen oder das Hauptadministrationsfenster zugreifen.',
        'assignedStations': 'Zugewiesene Stationen',
        'totalPresenters': 'Gesamte Moderatoren',
        'totalPrograms': 'Gesamte Programme',
        'totalRecordings': 'Gesamte Aufnahmen',
        'fetchError': 'Beim Laden der Daten ist ein Fehler aufgetreten. Bitte versuchen Sie, die Seite zu aktualisieren.',
        'noStationsTitle': 'Diesem Konto sind keine Stationen zugewiesen',
        'noStationsDesc': 'Wenden Sie sich an die Verwaltung, um Stationen für Ihr Konto zu aktivieren.',
        'yourAssignedStations': 'Ihre zugewiesenen Stationen',
        'active': 'Aktiv',
        'inactive': 'Inaktiv',
        'djCredsSet': 'Standard-DJ-Anmeldeinformationen festgelegt',
        'djCredsNotSet': 'Standard-DJ-Anmeldeinformationen nicht festgelegt',
        'presenters': 'Moderatoren',
        'programs': 'Programme',
        'recordings': 'Aufnahmen',
        'actions': 'Aktionen',
        'actionPresenters': 'Stationsmoderatoren',
        'actionPrograms': 'Stationsprogramme',
        'actionRecordings': 'Stationsaufnahmen',
        'actionDj': 'DJ-Einstellungen',
        'actionMedia': 'Medienbibliothek',
        'actionSchedule': 'Stationsprogramm',
        'open': 'Öffnen',
        'comingSoon': 'Demnächst'
    }
}

base_path = 'frontend/messages'

for lang in locales:
    file_path = os.path.join(base_path, f'{lang}.json')
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        if 'stationManager' not in data:
            data['stationManager'] = {}
        if 'dashboard' not in data['stationManager']:
            data['stationManager']['dashboard'] = {}
            
        data['stationManager']['dashboard'] = translations[lang]
        
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write('\n')

print("Station Manager Dashboard translations patched!")
