import json, os

locales = ['ar', 'en', 'fr', 'tr', 'pt', 'es', 'de']
translations = {
    'ar': {
        'title': 'مذيعو المحطة',
        'dashboard': 'اللوحة',
        'createdSuccess': 'تم إنشاء المذيع.',
        'opSuccess': 'تمت العملية.',
        'noAssignedTitle': 'لا توجد محطات مسندة',
        'noAssignedDesc': 'لم يتم إسناد أي محطة لحسابك. تواصل مع الإدارة لتفعيل صلاحياتك.',
        'allStations': 'كل المحطات',
        'searchPlaceholder': 'بحث باسم المذيع أو اسم المستخدم...',
        'addNew': 'إضافة مذيع جديد',
        'accountType': 'نوع الحساب:',
        'fullName': 'الاسم الكامل',
        'username': 'اسم المستخدم *',
        'email': 'البريد الإلكتروني',
        'phone': 'رقم الهاتف',
        'password': 'كلمة المرور *',
        'station': 'المحطة *',
        'selectStation': 'اختر محطة...',
        'createBtn': 'إنشاء المذيع',
        'presentersList': 'المذيعون',
        'noPresentersTitle': 'لا يوجد مذيعون مطابقون',
        'noPresentersDesc': 'جرب تعديل فلاتر البحث.',
        
        'cardUpdateSuccess': 'تم تعديل بيانات المذيع بنجاح.',
        'cardPwSuccess': 'تم تغيير كلمة مرور المذيع بنجاح.',
        'cardDeactivateSuccess': 'تم تعطيل الوصول بنجاح.',
        'multiStation': 'متعدد المحطات',
        'singleStation': 'محطة واحدة',
        'active': 'نشط',
        'inactive': 'معطّل',
        'manageAccessOnly': 'يمكنك إدارة وصوله لهذه المحطة فقط',
        'close': '▲ إغلاق',
        'edit': '✏️ تعديل',
        'passwordBtn': '🔑 كلمة المرور',
        'disableBtn': '🚫 تعطيل المذيع',
        'removeBtn': '🚫 إزالة من المحطة',
        'editData': 'تعديل بيانات المذيع',
        'status': 'الحالة',
        'saving': 'جارٍ الحفظ...',
        'saveChanges': 'حفظ التعديلات',
        'changePw': 'تغيير كلمة المرور',
        'newPw': 'كلمة المرور الجديدة *',
        'confirmPw': 'تأكيد كلمة المرور *',
        'pwMin': '6 أحرف على الأقل',
        'reEnter': 'أعد الإدخال',
        'changing': 'جارٍ التغيير...'
    },
    'en': {
        'title': 'Station Presenters',
        'dashboard': 'Dashboard',
        'createdSuccess': 'Presenter created successfully.',
        'opSuccess': 'Operation successful.',
        'noAssignedTitle': 'No assigned stations',
        'noAssignedDesc': 'No stations are assigned to your account. Contact administration to activate your permissions.',
        'allStations': 'All Stations',
        'searchPlaceholder': 'Search by presenter name or username...',
        'addNew': 'Add New Presenter',
        'accountType': 'Account Type:',
        'fullName': 'Full Name',
        'username': 'Username *',
        'email': 'Email',
        'phone': 'Phone Number',
        'password': 'Password *',
        'station': 'Station *',
        'selectStation': 'Select a station...',
        'createBtn': 'Create Presenter',
        'presentersList': 'Presenters',
        'noPresentersTitle': 'No matching presenters',
        'noPresentersDesc': 'Try adjusting search filters.',
        
        'cardUpdateSuccess': 'Presenter data updated successfully.',
        'cardPwSuccess': 'Presenter password changed successfully.',
        'cardDeactivateSuccess': 'Access disabled successfully.',
        'multiStation': 'Multi-Station',
        'singleStation': 'Single-Station',
        'active': 'Active',
        'inactive': 'Inactive',
        'manageAccessOnly': 'You can only manage their access to this station',
        'close': '▲ Close',
        'edit': '✏️ Edit',
        'passwordBtn': '🔑 Password',
        'disableBtn': '🚫 Disable Presenter',
        'removeBtn': '🚫 Remove from Station',
        'editData': 'Edit Presenter Data',
        'status': 'Status',
        'saving': 'Saving...',
        'saveChanges': 'Save Changes',
        'changePw': 'Change Password',
        'newPw': 'New Password *',
        'confirmPw': 'Confirm Password *',
        'pwMin': 'At least 6 characters',
        'reEnter': 'Re-enter',
        'changing': 'Changing...'
    },
    'fr': {
        'title': 'Présentateurs de la Station',
        'dashboard': 'Tableau de bord',
        'createdSuccess': 'Présentateur créé avec succès.',
        'opSuccess': 'Opération réussie.',
        'noAssignedTitle': 'Aucune station attribuée',
        'noAssignedDesc': 'Aucune station n\'est attribuée à votre compte. Contactez l\'administration pour activer vos autorisations.',
        'allStations': 'Toutes les Stations',
        'searchPlaceholder': 'Rechercher par nom ou nom d\'utilisateur...',
        'addNew': 'Ajouter un Présentateur',
        'accountType': 'Type de Compte:',
        'fullName': 'Nom Complet',
        'username': 'Nom d\'utilisateur *',
        'email': 'Email',
        'phone': 'Numéro de Téléphone',
        'password': 'Mot de passe *',
        'station': 'Station *',
        'selectStation': 'Sélectionnez une station...',
        'createBtn': 'Créer',
        'presentersList': 'Présentateurs',
        'noPresentersTitle': 'Aucun présentateur correspondant',
        'noPresentersDesc': 'Essayez d\'ajuster les filtres de recherche.',
        
        'cardUpdateSuccess': 'Données du présentateur mises à jour avec succès.',
        'cardPwSuccess': 'Mot de passe modifié avec succès.',
        'cardDeactivateSuccess': 'Accès désactivé avec succès.',
        'multiStation': 'Multi-Station',
        'singleStation': 'Station Unique',
        'active': 'Actif',
        'inactive': 'Inactif',
        'manageAccessOnly': 'Vous ne pouvez gérer que leur accès à cette station',
        'close': '▲ Fermer',
        'edit': '✏️ Modifier',
        'passwordBtn': '🔑 Mot de passe',
        'disableBtn': '🚫 Désactiver le Présentateur',
        'removeBtn': '🚫 Retirer de la Station',
        'editData': 'Modifier les Données',
        'status': 'Statut',
        'saving': 'Enregistrement...',
        'saveChanges': 'Enregistrer',
        'changePw': 'Changer le Mot de passe',
        'newPw': 'Nouveau Mot de passe *',
        'confirmPw': 'Confirmer *',
        'pwMin': 'Au moins 6 caractères',
        'reEnter': 'Ré-entrer',
        'changing': 'Modification...'
    },
    'tr': {
        'title': 'İstasyon Sunucuları',
        'dashboard': 'Pano',
        'createdSuccess': 'Sunucu başarıyla oluşturuldu.',
        'opSuccess': 'İşlem başarılı.',
        'noAssignedTitle': 'Atanmış istasyon yok',
        'noAssignedDesc': 'Hesabınıza atanmış istasyon yok. İzinlerinizi etkinleştirmek için yönetimle iletişime geçin.',
        'allStations': 'Tüm İstasyonlar',
        'searchPlaceholder': 'Sunucu adına veya kullanıcı adına göre ara...',
        'addNew': 'Yeni Sunucu Ekle',
        'accountType': 'Hesap Türü:',
        'fullName': 'Ad Soyad',
        'username': 'Kullanıcı Adı *',
        'email': 'E-posta',
        'phone': 'Telefon Numarası',
        'password': 'Şifre *',
        'station': 'İstasyon *',
        'selectStation': 'Bir istasyon seçin...',
        'createBtn': 'Sunucu Oluştur',
        'presentersList': 'Sunucular',
        'noPresentersTitle': 'Eşleşen sunucu yok',
        'noPresentersDesc': 'Arama filtrelerini ayarlamayı deneyin.',
        
        'cardUpdateSuccess': 'Sunucu verileri başarıyla güncellendi.',
        'cardPwSuccess': 'Sunucu şifresi başarıyla değiştirildi.',
        'cardDeactivateSuccess': 'Erişim başarıyla devre dışı bırakıldı.',
        'multiStation': 'Çoklu İstasyon',
        'singleStation': 'Tek İstasyon',
        'active': 'Aktif',
        'inactive': 'Pasif',
        'manageAccessOnly': 'Yalnızca bu istasyona erişimlerini yönetebilirsiniz',
        'close': '▲ Kapat',
        'edit': '✏️ Düzenle',
        'passwordBtn': '🔑 Şifre',
        'disableBtn': '🚫 Sunucuyu Devre Dışı Bırak',
        'removeBtn': '🚫 İstasyondan Çıkar',
        'editData': 'Sunucu Verilerini Düzenle',
        'status': 'Durum',
        'saving': 'Kaydediliyor...',
        'saveChanges': 'Değişiklikleri Kaydet',
        'changePw': 'Şifre Değiştir',
        'newPw': 'Yeni Şifre *',
        'confirmPw': 'Şifreyi Onayla *',
        'pwMin': 'En az 6 karakter',
        'reEnter': 'Tekrar girin',
        'changing': 'Değiştiriliyor...'
    },
    'pt': {
        'title': 'Apresentadores da Estação',
        'dashboard': 'Painel',
        'createdSuccess': 'Apresentador criado com sucesso.',
        'opSuccess': 'Operação bem-sucedida.',
        'noAssignedTitle': 'Nenhuma estação atribuída',
        'noAssignedDesc': 'Nenhuma estação está atribuída à sua conta. Contate a administração para ativar suas permissões.',
        'allStations': 'Todas as Estações',
        'searchPlaceholder': 'Pesquisar por nome ou nome de usuário...',
        'addNew': 'Adicionar Novo Apresentador',
        'accountType': 'Tipo de Conta:',
        'fullName': 'Nome Completo',
        'username': 'Nome de Usuário *',
        'email': 'Email',
        'phone': 'Número de Telefone',
        'password': 'Senha *',
        'station': 'Estação *',
        'selectStation': 'Selecione uma estação...',
        'createBtn': 'Criar Apresentador',
        'presentersList': 'Apresentadores',
        'noPresentersTitle': 'Nenhum apresentador correspondente',
        'noPresentersDesc': 'Tente ajustar os filtros de pesquisa.',
        
        'cardUpdateSuccess': 'Dados do apresentador atualizados com sucesso.',
        'cardPwSuccess': 'Senha do apresentador alterada com sucesso.',
        'cardDeactivateSuccess': 'Acesso desativado com sucesso.',
        'multiStation': 'Multi-Estação',
        'singleStation': 'Estação Única',
        'active': 'Ativo',
        'inactive': 'Inativo',
        'manageAccessOnly': 'Você só pode gerenciar o acesso deles a esta estação',
        'close': '▲ Fechar',
        'edit': '✏️ Editar',
        'passwordBtn': '🔑 Senha',
        'disableBtn': '🚫 Desativar Apresentador',
        'removeBtn': '🚫 Remover da Estação',
        'editData': 'Editar Dados',
        'status': 'Status',
        'saving': 'Salvando...',
        'saveChanges': 'Salvar Alterações',
        'changePw': 'Mudar Senha',
        'newPw': 'Nova Senha *',
        'confirmPw': 'Confirmar Senha *',
        'pwMin': 'Pelo menos 6 caracteres',
        'reEnter': 'Insira novamente',
        'changing': 'Alterando...'
    },
    'es': {
        'title': 'Presentadores de la Estación',
        'dashboard': 'Panel',
        'createdSuccess': 'Presentador creado con éxito.',
        'opSuccess': 'Operación exitosa.',
        'noAssignedTitle': 'No hay estaciones asignadas',
        'noAssignedDesc': 'No hay estaciones asignadas a tu cuenta. Contacta con la administración para activar tus permisos.',
        'allStations': 'Todas las Estaciones',
        'searchPlaceholder': 'Buscar por nombre o usuario...',
        'addNew': 'Añadir Nuevo Presentador',
        'accountType': 'Tipo de Cuenta:',
        'fullName': 'Nombre Completo',
        'username': 'Usuario *',
        'email': 'Correo electrónico',
        'phone': 'Número de Teléfono',
        'password': 'Contraseña *',
        'station': 'Estación *',
        'selectStation': 'Selecciona una estación...',
        'createBtn': 'Crear Presentador',
        'presentersList': 'Presentadores',
        'noPresentersTitle': 'No hay presentadores que coincidan',
        'noPresentersDesc': 'Intenta ajustar los filtros de búsqueda.',
        
        'cardUpdateSuccess': 'Datos actualizados con éxito.',
        'cardPwSuccess': 'Contraseña cambiada con éxito.',
        'cardDeactivateSuccess': 'Acceso desactivado con éxito.',
        'multiStation': 'Multi-Estación',
        'singleStation': 'Estación Única',
        'active': 'Activo',
        'inactive': 'Inactivo',
        'manageAccessOnly': 'Solo puedes gestionar su acceso a esta estación',
        'close': '▲ Cerrar',
        'edit': '✏️ Editar',
        'passwordBtn': '🔑 Contraseña',
        'disableBtn': '🚫 Desactivar Presentador',
        'removeBtn': '🚫 Eliminar de la Estación',
        'editData': 'Editar Datos',
        'status': 'Estado',
        'saving': 'Guardando...',
        'saveChanges': 'Guardar Cambios',
        'changePw': 'Cambiar Contraseña',
        'newPw': 'Nueva Contraseña *',
        'confirmPw': 'Confirmar Contraseña *',
        'pwMin': 'Al menos 6 caracteres',
        'reEnter': 'Vuelve a introducir',
        'changing': 'Cambiando...'
    },
    'de': {
        'title': 'Stationsmoderatoren',
        'dashboard': 'Dashboard',
        'createdSuccess': 'Moderator erfolgreich erstellt.',
        'opSuccess': 'Vorgang erfolgreich.',
        'noAssignedTitle': 'Keine zugewiesenen Stationen',
        'noAssignedDesc': 'Ihrem Konto sind keine Stationen zugewiesen. Wenden Sie sich an die Verwaltung, um Ihre Berechtigungen zu aktivieren.',
        'allStations': 'Alle Stationen',
        'searchPlaceholder': 'Suche nach Name oder Benutzername...',
        'addNew': 'Neuen Moderator hinzufügen',
        'accountType': 'Kontotyp:',
        'fullName': 'Vollständiger Name',
        'username': 'Benutzername *',
        'email': 'E-Mail',
        'phone': 'Telefonnummer',
        'password': 'Passwort *',
        'station': 'Station *',
        'selectStation': 'Wählen Sie eine Station...',
        'createBtn': 'Moderator erstellen',
        'presentersList': 'Moderatoren',
        'noPresentersTitle': 'Keine übereinstimmenden Moderatoren',
        'noPresentersDesc': 'Versuchen Sie, die Suchfilter anzupassen.',
        
        'cardUpdateSuccess': 'Moderatordaten erfolgreich aktualisiert.',
        'cardPwSuccess': 'Passwort erfolgreich geändert.',
        'cardDeactivateSuccess': 'Zugriff erfolgreich deaktiviert.',
        'multiStation': 'Multi-Station',
        'singleStation': 'Einzel-Station',
        'active': 'Aktiv',
        'inactive': 'Inaktiv',
        'manageAccessOnly': 'Sie können nur deren Zugriff auf diese Station verwalten',
        'close': '▲ Schließen',
        'edit': '✏️ Bearbeiten',
        'passwordBtn': '🔑 Passwort',
        'disableBtn': '🚫 Moderator deaktivieren',
        'removeBtn': '🚫 Aus Station entfernen',
        'editData': 'Daten bearbeiten',
        'status': 'Status',
        'saving': 'Speichern...',
        'saveChanges': 'Änderungen speichern',
        'changePw': 'Passwort ändern',
        'newPw': 'Neues Passwort *',
        'confirmPw': 'Passwort bestätigen *',
        'pwMin': 'Mindestens 6 Zeichen',
        'reEnter': 'Erneut eingeben',
        'changing': 'Ändern...'
    }
}

base_path = 'frontend/messages'

for lang in locales:
    file_path = os.path.join(base_path, f'{lang}.json')
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        if 'stationManager' not in data:
            data['stationManager'] = {}
        if 'presenters' not in data['stationManager']:
            data['stationManager']['presenters'] = {}
            
        data['stationManager']['presenters'] = translations[lang]
        
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write('\n')

print("Translations patched!")
