import json, os

locales = ['ar', 'en', 'fr', 'tr', 'pt', 'es', 'de']
translations = {
    'ar': {
        'title': 'برامج المحطة - EGONAIR',
        'stationManager': 'مدير المحطة',
        'dashboard': 'اللوحة',
        'heading': 'برامج المحطة',
        'opSuccess': 'تمت العملية بنجاح.',
        'noAssignedTitle': 'لا توجد محطات مسندة',
        'noAssignedDesc': 'لم يتم إسناد أي محطة لحسابك. تواصل مع الإدارة لتفعيل صلاحياتك.',
        'addNew': 'إضافة برنامج جديد',
        'programTitle': 'عنوان البرنامج *',
        'station': 'المحطة *',
        'selectStation': 'اختر محطة...',
        'presenter': 'المذيع *',
        'selectPresenter': 'اختر مذيعاً...',
        'createBtn': 'إنشاء البرنامج',
        'allStations': 'كل المحطات',
        'statusAll': 'الكل',
        'statusActive': 'نشطة',
        'statusInactive': 'معطّلة',
        'searchPlaceholder': 'بحث في البرامج...',
        'programsList': 'البرامج',
        'noMatchTitle': 'لا توجد برامج مطابقة',
        'noMatchDesc': 'جرب تعديل فلاتر البحث.',
        'noProgramsTitle': 'لا توجد برامج بعد',
        'noProgramsDesc': 'ستظهر هنا برامج المحطة بعد إنشائها.',
        
        'daily': 'يومي',
        'weekly': 'أسبوعي',
        'selectedDays': 'أيام محددة',
        'oneTime': 'حلقة واحدة',
        'progUpdated': 'تم تعديل البرنامج.',
        'progActivated': 'تم تفعيل البرنامج.',
        'progDisabled': 'تم تعطيل البرنامج.',
        'progDisabledPerm': 'تم تعطيل البرنامج نهائياً.',
        'ruleAdded': 'تمت إضافة قاعدة البث.',
        'ruleUpdated': 'تم تعديل القاعدة.',
        'timeAdded': 'تمت إضافة الوقت.',
        'timeUpdated': 'تم تعديل الوقت.',
        'timeDeleted': 'تم حذف الوقت.',
        'active': 'نشط',
        'inactive': 'معطّل',
        'inactiveFem': 'معطّلة',
        'close': '▲ إغلاق',
        'edit': '✏️ تعديل',
        'scheduleBtn': '📅 الجدول',
        'disable': 'تعطيل',
        'enable': 'تفعيل',
        'disablePerm': '🚫 تعطيل نهائي',
        'editData': 'تعديل بيانات البرنامج',
        'description': 'الوصف',
        'status': 'الحالة',
        'cancel': 'إلغاء',
        'saving': 'جارٍ الحفظ...',
        'saveChanges': 'حفظ التعديلات',
        'progSchedule': '📅 جدول البرنامج',
        'conflictNote': 'سيتم فحص التضارب من نظام الجدولة العام.',
        'noRules': 'لا توجد قواعد بث بعد.',
        'enter': 'دخول',
        'minBefore': 'د قبل',
        'ruleInactive': '(معطّلة)',
        'editRule': '✏️ تعديل القاعدة',
        'addTime': '+ إضافة وقت',
        'addTimeBtn': 'إضافة الوقت',
        'recType': 'نوع التكرار *',
        'timezone': 'المنطقة الزمنية',
        'earlyMins': 'دقائق الدخول المبكر',
        'saveRule': 'حفظ تعديل القاعدة',
        'noTimes': 'لا توجد أوقات.',
        'timeInactive': '(معطّل)',
        'editTime': '✏️ تعديل الوقت',
        'delete': '✕ حذف',
        'day': 'اليوم',
        'date': 'التاريخ',
        'from': 'من *',
        'to': 'إلى *',
        'saveTime': 'حفظ تعديل الوقت',
        'addNewRule': '+ إضافة قاعدة بث جديدة',
        'adding': 'جارٍ الإضافة...',
        'addRuleBtn': 'إضافة القاعدة',
        
        'sun': 'الأحد',
        'mon': 'الاثنين',
        'tue': 'الثلاثاء',
        'wed': 'الأربعاء',
        'thu': 'الخميس',
        'fri': 'الجمعة',
        'sat': 'السبت'
    },
    'en': {
        'title': 'Station Programs - EGONAIR',
        'stationManager': 'Station Manager',
        'dashboard': 'Dashboard',
        'heading': 'Station Programs',
        'opSuccess': 'Operation successful.',
        'noAssignedTitle': 'No assigned stations',
        'noAssignedDesc': 'No stations are assigned to your account. Contact administration to activate your permissions.',
        'addNew': 'Add New Program',
        'programTitle': 'Program Title *',
        'station': 'Station *',
        'selectStation': 'Select a station...',
        'presenter': 'Presenter *',
        'selectPresenter': 'Select a presenter...',
        'createBtn': 'Create Program',
        'allStations': 'All Stations',
        'statusAll': 'All',
        'statusActive': 'Active',
        'statusInactive': 'Inactive',
        'searchPlaceholder': 'Search programs...',
        'programsList': 'Programs',
        'noMatchTitle': 'No matching programs',
        'noMatchDesc': 'Try adjusting search filters.',
        'noProgramsTitle': 'No programs yet',
        'noProgramsDesc': 'Station programs will appear here after creation.',
        
        'daily': 'Daily',
        'weekly': 'Weekly',
        'selectedDays': 'Selected Days',
        'oneTime': 'One Time',
        'progUpdated': 'Program updated.',
        'progActivated': 'Program activated.',
        'progDisabled': 'Program disabled.',
        'progDisabledPerm': 'Program disabled permanently.',
        'ruleAdded': 'Schedule rule added.',
        'ruleUpdated': 'Rule updated.',
        'timeAdded': 'Time added.',
        'timeUpdated': 'Time updated.',
        'timeDeleted': 'Time deleted.',
        'active': 'Active',
        'inactive': 'Inactive',
        'inactiveFem': 'Inactive',
        'close': '▲ Close',
        'edit': '✏️ Edit',
        'scheduleBtn': '📅 Schedule',
        'disable': 'Disable',
        'enable': 'Enable',
        'disablePerm': '🚫 Disable Permanently',
        'editData': 'Edit Program Data',
        'description': 'Description',
        'status': 'Status',
        'cancel': 'Cancel',
        'saving': 'Saving...',
        'saveChanges': 'Save Changes',
        'progSchedule': '📅 Program Schedule',
        'conflictNote': 'Conflicts will be checked against the global scheduling system.',
        'noRules': 'No schedule rules yet.',
        'enter': 'Enter',
        'minBefore': 'min before',
        'ruleInactive': '(Inactive)',
        'editRule': '✏️ Edit Rule',
        'addTime': '+ Add Time',
        'addTimeBtn': 'Add Time',
        'recType': 'Recurrence Type *',
        'timezone': 'Timezone',
        'earlyMins': 'Early Entry Minutes',
        'saveRule': 'Save Rule Change',
        'noTimes': 'No times.',
        'timeInactive': '(Inactive)',
        'editTime': '✏️ Edit Time',
        'delete': '✕ Delete',
        'day': 'Day',
        'date': 'Date',
        'from': 'From *',
        'to': 'To *',
        'saveTime': 'Save Time Change',
        'addNewRule': '+ Add New Schedule Rule',
        'adding': 'Adding...',
        'addRuleBtn': 'Add Rule',
        
        'sun': 'Sunday',
        'mon': 'Monday',
        'tue': 'Tuesday',
        'wed': 'Wednesday',
        'thu': 'Thursday',
        'fri': 'Friday',
        'sat': 'Saturday'
    },
    'fr': {
        'title': 'Programmes de la Station - EGONAIR',
        'stationManager': 'Responsable de la station',
        'dashboard': 'Tableau de bord',
        'heading': 'Programmes de la Station',
        'opSuccess': 'Opération réussie.',
        'noAssignedTitle': 'Aucune station assignée',
        'noAssignedDesc': 'Aucune station n\'est assignée à votre compte. Contactez l\'administration pour activer vos permissions.',
        'addNew': 'Ajouter un nouveau programme',
        'programTitle': 'Titre du programme *',
        'station': 'Station *',
        'selectStation': 'Sélectionnez une station...',
        'presenter': 'Présentateur *',
        'selectPresenter': 'Sélectionnez un présentateur...',
        'createBtn': 'Créer le programme',
        'allStations': 'Toutes les stations',
        'statusAll': 'Tous',
        'statusActive': 'Actifs',
        'statusInactive': 'Inactifs',
        'searchPlaceholder': 'Rechercher des programmes...',
        'programsList': 'Programmes',
        'noMatchTitle': 'Aucun programme correspondant',
        'noMatchDesc': 'Essayez d\'ajuster les filtres de recherche.',
        'noProgramsTitle': 'Aucun programme pour le moment',
        'noProgramsDesc': 'Les programmes de la station apparaîtront ici après leur création.',
        
        'daily': 'Quotidien',
        'weekly': 'Hebdomadaire',
        'selectedDays': 'Jours sélectionnés',
        'oneTime': 'Une fois',
        'progUpdated': 'Programme mis à jour.',
        'progActivated': 'Programme activé.',
        'progDisabled': 'Programme désactivé.',
        'progDisabledPerm': 'Programme désactivé de façon permanente.',
        'ruleAdded': 'Règle de planification ajoutée.',
        'ruleUpdated': 'Règle mise à jour.',
        'timeAdded': 'Heure ajoutée.',
        'timeUpdated': 'Heure mise à jour.',
        'timeDeleted': 'Heure supprimée.',
        'active': 'Actif',
        'inactive': 'Inactif',
        'inactiveFem': 'Inactive',
        'close': '▲ Fermer',
        'edit': '✏️ Modifier',
        'scheduleBtn': '📅 Calendrier',
        'disable': 'Désactiver',
        'enable': 'Activer',
        'disablePerm': '🚫 Désactiver de façon permanente',
        'editData': 'Modifier les données du programme',
        'description': 'Description',
        'status': 'Statut',
        'cancel': 'Annuler',
        'saving': 'Enregistrement...',
        'saveChanges': 'Enregistrer les modifications',
        'progSchedule': '📅 Calendrier du programme',
        'conflictNote': 'Les conflits seront vérifiés par rapport au système de planification global.',
        'noRules': 'Aucune règle de planification pour le moment.',
        'enter': 'Entrer',
        'minBefore': 'min avant',
        'ruleInactive': '(Inactif)',
        'editRule': '✏️ Modifier la règle',
        'addTime': '+ Ajouter l\'heure',
        'addTimeBtn': 'Ajouter l\'heure',
        'recType': 'Type de récurrence *',
        'timezone': 'Fuseau horaire',
        'earlyMins': 'Minutes d\'entrée anticipée',
        'saveRule': 'Enregistrer la modification de la règle',
        'noTimes': 'Aucune heure.',
        'timeInactive': '(Inactif)',
        'editTime': '✏️ Modifier l\'heure',
        'delete': '✕ Supprimer',
        'day': 'Jour',
        'date': 'Date',
        'from': 'De *',
        'to': 'À *',
        'saveTime': 'Enregistrer la modification de l\'heure',
        'addNewRule': '+ Ajouter une nouvelle règle de planification',
        'adding': 'Ajout...',
        'addRuleBtn': 'Ajouter la règle',
        
        'sun': 'Dimanche',
        'mon': 'Lundi',
        'tue': 'Mardi',
        'wed': 'Mercredi',
        'thu': 'Jeudi',
        'fri': 'Vendredi',
        'sat': 'Samedi'
    },
    'tr': {
        'title': 'İstasyon Programları - EGONAIR',
        'stationManager': 'İstasyon Yöneticisi',
        'dashboard': 'Pano',
        'heading': 'İstasyon Programları',
        'opSuccess': 'İşlem başarılı.',
        'noAssignedTitle': 'Atanmış istasyon yok',
        'noAssignedDesc': 'Hesabınıza atanmış istasyon yok. İzinlerinizi etkinleştirmek için yönetimle iletişime geçin.',
        'addNew': 'Yeni Program Ekle',
        'programTitle': 'Program Başlığı *',
        'station': 'İstasyon *',
        'selectStation': 'Bir istasyon seçin...',
        'presenter': 'Sunucu *',
        'selectPresenter': 'Bir sunucu seçin...',
        'createBtn': 'Program Oluştur',
        'allStations': 'Tüm İstasyonlar',
        'statusAll': 'Tümü',
        'statusActive': 'Aktif',
        'statusInactive': 'Pasif',
        'searchPlaceholder': 'Programlarda ara...',
        'programsList': 'Programlar',
        'noMatchTitle': 'Eşleşen program yok',
        'noMatchDesc': 'Arama filtrelerini ayarlamayı deneyin.',
        'noProgramsTitle': 'Henüz program yok',
        'noProgramsDesc': 'İstasyon programları oluşturulduktan sonra burada görünecektir.',
        
        'daily': 'Günlük',
        'weekly': 'Haftalık',
        'selectedDays': 'Seçili Günler',
        'oneTime': 'Bir Kez',
        'progUpdated': 'Program güncellendi.',
        'progActivated': 'Program etkinleştirildi.',
        'progDisabled': 'Program devre dışı bırakıldı.',
        'progDisabledPerm': 'Program kalıcı olarak devre dışı bırakıldı.',
        'ruleAdded': 'Zamanlama kuralı eklendi.',
        'ruleUpdated': 'Kural güncellendi.',
        'timeAdded': 'Zaman eklendi.',
        'timeUpdated': 'Zaman güncellendi.',
        'timeDeleted': 'Zaman silindi.',
        'active': 'Aktif',
        'inactive': 'Pasif',
        'inactiveFem': 'Pasif',
        'close': '▲ Kapat',
        'edit': '✏️ Düzenle',
        'scheduleBtn': '📅 Zamanlama',
        'disable': 'Devre Dışı Bırak',
        'enable': 'Etkinleştir',
        'disablePerm': '🚫 Kalıcı Olarak Devre Dışı Bırak',
        'editData': 'Program Verilerini Düzenle',
        'description': 'Açıklama',
        'status': 'Durum',
        'cancel': 'İptal',
        'saving': 'Kaydediliyor...',
        'saveChanges': 'Değişiklikleri Kaydet',
        'progSchedule': '📅 Program Zamanlaması',
        'conflictNote': 'Çakışmalar küresel zamanlama sistemine karşı kontrol edilecektir.',
        'noRules': 'Henüz zamanlama kuralı yok.',
        'enter': 'Giriş',
        'minBefore': 'dk önce',
        'ruleInactive': '(Pasif)',
        'editRule': '✏️ Kuralı Düzenle',
        'addTime': '+ Zaman Ekle',
        'addTimeBtn': 'Zaman Ekle',
        'recType': 'Tekrarlama Türü *',
        'timezone': 'Saat Dilimi',
        'earlyMins': 'Erken Giriş Dakikaları',
        'saveRule': 'Kural Değişikliğini Kaydet',
        'noTimes': 'Zaman yok.',
        'timeInactive': '(Pasif)',
        'editTime': '✏️ Zamanı Düzenle',
        'delete': '✕ Sil',
        'day': 'Gün',
        'date': 'Tarih',
        'from': 'Başlangıç *',
        'to': 'Bitiş *',
        'saveTime': 'Zaman Değişikliğini Kaydet',
        'addNewRule': '+ Yeni Zamanlama Kuralı Ekle',
        'adding': 'Ekleniyor...',
        'addRuleBtn': 'Kural Ekle',
        
        'sun': 'Pazar',
        'mon': 'Pazartesi',
        'tue': 'Salı',
        'wed': 'Çarşamba',
        'thu': 'Perşembe',
        'fri': 'Cuma',
        'sat': 'Cumartesi'
    },
    'pt': {
        'title': 'Programas da Estação - EGONAIR',
        'stationManager': 'Gerente da Estação',
        'dashboard': 'Painel',
        'heading': 'Programas da Estação',
        'opSuccess': 'Operação bem-sucedida.',
        'noAssignedTitle': 'Nenhuma estação atribuída',
        'noAssignedDesc': 'Nenhuma estação está atribuída à sua conta. Entre em contato com a administração para ativar suas permissões.',
        'addNew': 'Adicionar Novo Programa',
        'programTitle': 'Título do Programa *',
        'station': 'Estação *',
        'selectStation': 'Selecione uma estação...',
        'presenter': 'Apresentador *',
        'selectPresenter': 'Selecione um apresentador...',
        'createBtn': 'Criar Programa',
        'allStations': 'Todas as Estações',
        'statusAll': 'Todos',
        'statusActive': 'Ativos',
        'statusInactive': 'Inativos',
        'searchPlaceholder': 'Pesquisar programas...',
        'programsList': 'Programas',
        'noMatchTitle': 'Nenhum programa correspondente',
        'noMatchDesc': 'Tente ajustar os filtros de pesquisa.',
        'noProgramsTitle': 'Nenhum programa ainda',
        'noProgramsDesc': 'Os programas da estação aparecerão aqui após a criação.',
        
        'daily': 'Diário',
        'weekly': 'Semanal',
        'selectedDays': 'Dias Selecionados',
        'oneTime': 'Uma Vez',
        'progUpdated': 'Programa atualizado.',
        'progActivated': 'Programa ativado.',
        'progDisabled': 'Programa desativado.',
        'progDisabledPerm': 'Programa desativado permanentemente.',
        'ruleAdded': 'Regra de programação adicionada.',
        'ruleUpdated': 'Regra atualizada.',
        'timeAdded': 'Tempo adicionado.',
        'timeUpdated': 'Tempo atualizado.',
        'timeDeleted': 'Tempo excluído.',
        'active': 'Ativo',
        'inactive': 'Inativo',
        'inactiveFem': 'Inativo',
        'close': '▲ Fechar',
        'edit': '✏️ Editar',
        'scheduleBtn': '📅 Cronograma',
        'disable': 'Desativar',
        'enable': 'Ativar',
        'disablePerm': '🚫 Desativar Permanentemente',
        'editData': 'Editar Dados do Programa',
        'description': 'Descrição',
        'status': 'Status',
        'cancel': 'Cancelar',
        'saving': 'Salvando...',
        'saveChanges': 'Salvar Alterações',
        'progSchedule': '📅 Cronograma do Programa',
        'conflictNote': 'Conflitos serão verificados contra o sistema de agendamento global.',
        'noRules': 'Nenhuma regra de programação ainda.',
        'enter': 'Entrar',
        'minBefore': 'min antes',
        'ruleInactive': '(Inativo)',
        'editRule': '✏️ Editar Regra',
        'addTime': '+ Adicionar Tempo',
        'addTimeBtn': 'Adicionar Tempo',
        'recType': 'Tipo de Recorrência *',
        'timezone': 'Fuso Horário',
        'earlyMins': 'Minutos de Entrada Antecipada',
        'saveRule': 'Salvar Alteração de Regra',
        'noTimes': 'Sem tempos.',
        'timeInactive': '(Inativo)',
        'editTime': '✏️ Editar Tempo',
        'delete': '✕ Excluir',
        'day': 'Dia',
        'date': 'Data',
        'from': 'De *',
        'to': 'Para *',
        'saveTime': 'Salvar Alteração de Tempo',
        'addNewRule': '+ Adicionar Nova Regra',
        'adding': 'Adicionando...',
        'addRuleBtn': 'Adicionar Regra',
        
        'sun': 'Domingo',
        'mon': 'Segunda-feira',
        'tue': 'Terça-feira',
        'wed': 'Quarta-feira',
        'thu': 'Quinta-feira',
        'fri': 'Sexta-feira',
        'sat': 'Sábado'
    },
    'es': {
        'title': 'Programas de la Estación - EGONAIR',
        'stationManager': 'Gerente de la Estación',
        'dashboard': 'Panel',
        'heading': 'Programas de la Estación',
        'opSuccess': 'Operación exitosa.',
        'noAssignedTitle': 'No hay estaciones asignadas',
        'noAssignedDesc': 'No hay estaciones asignadas a tu cuenta. Contacta con la administración para activar tus permisos.',
        'addNew': 'Añadir Nuevo Programa',
        'programTitle': 'Título del Programa *',
        'station': 'Estación *',
        'selectStation': 'Selecciona una estación...',
        'presenter': 'Presentador *',
        'selectPresenter': 'Selecciona un presentador...',
        'createBtn': 'Crear Programa',
        'allStations': 'Todas las Estaciones',
        'statusAll': 'Todos',
        'statusActive': 'Activos',
        'statusInactive': 'Inactivos',
        'searchPlaceholder': 'Buscar programas...',
        'programsList': 'Programas',
        'noMatchTitle': 'No hay programas que coincidan',
        'noMatchDesc': 'Intenta ajustar los filtros de búsqueda.',
        'noProgramsTitle': 'Aún no hay programas',
        'noProgramsDesc': 'Los programas de la estación aparecerán aquí después de su creación.',
        
        'daily': 'Diario',
        'weekly': 'Semanal',
        'selectedDays': 'Días Seleccionados',
        'oneTime': 'Una Vez',
        'progUpdated': 'Programa actualizado.',
        'progActivated': 'Programa activado.',
        'progDisabled': 'Programa desactivado.',
        'progDisabledPerm': 'Programa desactivado permanentemente.',
        'ruleAdded': 'Regla de programación añadida.',
        'ruleUpdated': 'Regla actualizada.',
        'timeAdded': 'Tiempo añadido.',
        'timeUpdated': 'Tiempo actualizado.',
        'timeDeleted': 'Tiempo eliminado.',
        'active': 'Activo',
        'inactive': 'Inactivo',
        'inactiveFem': 'Inactivo',
        'close': '▲ Cerrar',
        'edit': '✏️ Editar',
        'scheduleBtn': '📅 Horario',
        'disable': 'Desactivar',
        'enable': 'Activar',
        'disablePerm': '🚫 Desactivar Permanentemente',
        'editData': 'Editar Datos del Programa',
        'description': 'Descripción',
        'status': 'Estado',
        'cancel': 'Cancelar',
        'saving': 'Guardando...',
        'saveChanges': 'Guardar Cambios',
        'progSchedule': '📅 Horario del Programa',
        'conflictNote': 'Los conflictos se comprobarán con el sistema de programación global.',
        'noRules': 'Aún no hay reglas de programación.',
        'enter': 'Entrar',
        'minBefore': 'min antes',
        'ruleInactive': '(Inactivo)',
        'editRule': '✏️ Editar Regla',
        'addTime': '+ Añadir Tiempo',
        'addTimeBtn': 'Añadir Tiempo',
        'recType': 'Tipo de Recurrencia *',
        'timezone': 'Zona Horaria',
        'earlyMins': 'Minutos de Entrada Anticipada',
        'saveRule': 'Guardar Cambio de Regra',
        'noTimes': 'No hay tiempos.',
        'timeInactive': '(Inactivo)',
        'editTime': '✏️ Editar Tiempo',
        'delete': '✕ Eliminar',
        'day': 'Día',
        'date': 'Fecha',
        'from': 'De *',
        'to': 'A *',
        'saveTime': 'Guardar Cambio de Tiempo',
        'addNewRule': '+ Añadir Nueva Regla',
        'adding': 'Añadiendo...',
        'addRuleBtn': 'Añadir Regla',
        
        'sun': 'Domingo',
        'mon': 'Lunes',
        'tue': 'Martes',
        'wed': 'Miércoles',
        'thu': 'Jueves',
        'fri': 'Viernes',
        'sat': 'Sábado'
    },
    'de': {
        'title': 'Stationsprogramme - EGONAIR',
        'stationManager': 'Stationsleiter',
        'dashboard': 'Dashboard',
        'heading': 'Stationsprogramme',
        'opSuccess': 'Vorgang erfolgreich.',
        'noAssignedTitle': 'Keine zugewiesenen Stationen',
        'noAssignedDesc': 'Ihrem Konto sind keine Stationen zugewiesen. Wenden Sie sich an die Verwaltung, um Ihre Berechtigungen zu aktivieren.',
        'addNew': 'Neues Programm hinzufügen',
        'programTitle': 'Programmtitel *',
        'station': 'Station *',
        'selectStation': 'Wählen Sie eine Station...',
        'presenter': 'Moderator *',
        'selectPresenter': 'Wählen Sie einen Moderator...',
        'createBtn': 'Programm erstellen',
        'allStations': 'Alle Stationen',
        'statusAll': 'Alle',
        'statusActive': 'Aktiv',
        'statusInactive': 'Inaktiv',
        'searchPlaceholder': 'Programme suchen...',
        'programsList': 'Programme',
        'noMatchTitle': 'Keine übereinstimmenden Programme',
        'noMatchDesc': 'Versuchen Sie, die Suchfilter anzupassen.',
        'noProgramsTitle': 'Noch keine Programme',
        'noProgramsDesc': 'Stationsprogramme werden hier nach der Erstellung angezeigt.',
        
        'daily': 'Täglich',
        'weekly': 'Wöchentlich',
        'selectedDays': 'Ausgewählte Tage',
        'oneTime': 'Einmalig',
        'progUpdated': 'Programm aktualisiert.',
        'progActivated': 'Programm aktiviert.',
        'progDisabled': 'Programm deaktiviert.',
        'progDisabledPerm': 'Programm dauerhaft deaktiviert.',
        'ruleAdded': 'Zeitplanregel hinzugefügt.',
        'ruleUpdated': 'Regel aktualisiert.',
        'timeAdded': 'Zeit hinzugefügt.',
        'timeUpdated': 'Zeit aktualisiert.',
        'timeDeleted': 'Zeit gelöscht.',
        'active': 'Aktiv',
        'inactive': 'Inaktiv',
        'inactiveFem': 'Inaktiv',
        'close': '▲ Schließen',
        'edit': '✏️ Bearbeiten',
        'scheduleBtn': '📅 Zeitplan',
        'disable': 'Deaktivieren',
        'enable': 'Aktivieren',
        'disablePerm': '🚫 Dauerhaft deaktivieren',
        'editData': 'Programmdaten bearbeiten',
        'description': 'Beschreibung',
        'status': 'Status',
        'cancel': 'Abbrechen',
        'saving': 'Speichern...',
        'saveChanges': 'Änderungen speichern',
        'progSchedule': '📅 Programmzeitplan',
        'conflictNote': 'Konflikte werden mit dem globalen Zeitplansystem überprüft.',
        'noRules': 'Noch keine Zeitplanregeln.',
        'enter': 'Eintreten',
        'minBefore': 'Min zuvor',
        'ruleInactive': '(Inaktiv)',
        'editRule': '✏️ Regel bearbeiten',
        'addTime': '+ Zeit hinzufügen',
        'addTimeBtn': 'Zeit hinzufügen',
        'recType': 'Wiederholungstyp *',
        'timezone': 'Zeitzone',
        'earlyMins': 'Frühe Eintrittsminuten',
        'saveRule': 'Regeländerung speichern',
        'noTimes': 'Keine Zeiten.',
        'timeInactive': '(Inaktiv)',
        'editTime': '✏️ Zeit bearbeiten',
        'delete': '✕ Löschen',
        'day': 'Tag',
        'date': 'Datum',
        'from': 'Von *',
        'to': 'Bis *',
        'saveTime': 'Zeitänderung speichern',
        'addNewRule': '+ Neue Zeitplanregel hinzufügen',
        'adding': 'Hinzufügen...',
        'addRuleBtn': 'Regel hinzufügen',
        
        'sun': 'Sonntag',
        'mon': 'Montag',
        'tue': 'Dienstag',
        'wed': 'Mittwoch',
        'thu': 'Donnerstag',
        'fri': 'Freitag',
        'sat': 'Samstag'
    }
}

base_path = 'frontend/messages'

for lang in locales:
    file_path = os.path.join(base_path, f'{lang}.json')
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        if 'stationManager' not in data:
            data['stationManager'] = {}
        if 'programs' not in data['stationManager']:
            data['stationManager']['programs'] = {}
            
        data['stationManager']['programs'] = translations[lang]
        
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write('\n')

print("Translations patched for stationManager.programs!")
