import json
import os

langs = {
  "ar.json": {
    "title": "تدقيق الجداول للإدارة", "titleMain": "تدقيق الجداول والإعدادات", "subtitle": "فحص شامل للتداخلات والأخطاء — للقراءة فقط، لا يُعدَّل أي بيانات.", "back": "← عودة", "all": "الكل", "errors": "⛔ أخطاء", "warnings": "⚠️ تحذيرات", "stationLabel": "المحطة:", "issueType": "نوع المشكلة:", "clearFilters": "✕ مسح الفلاتر ({count} نتيجة)", "criticalErrors": "أخطاء حرجة", "warningsCount": "تحذيرات", "activePrograms": "إجمالي البرامج النشطة", "noIssues": "لا توجد مشكلات مكتشفة", "noIssuesDesc": "كل الجداول والمذيعين والمحطات تبدو سليمة.", "legendTitle": "الفحوصات المُنفَّذة في هذا التقرير:",
    "typeA": "تداخل جدول في نفس المحطة", "descA": "«{titleA}» و«{titleB}» على «{station}» ({startA}–{endA} ↔ {startB}–{endB})", "suggA": "عدّل مواعيد أحد البرنامجين لإزالة التداخل.", "legendA": "A — تداخل مواعيد برنامجين على نفس المحطة",
    "typeB": "تداخل جدول نفس المذيع (محطتان)", "descB": "المذيع «{presenter}» جُدول في برنامجين في نفس الوقت عبر محطتين مختلفتين.", "suggB": "المذيع لا يمكنه البث على محطتين في نفس الوقت.", "legendB": "B — نفس المذيع جُدول في برنامجين في نفس الوقت (عبر محطتين)",
    "typeC": "مذيع غير مرتبط بمحطة البرنامج", "descC": "البرنامج «{program}» مرتبط بمذيع لم يُضَف لمحطة «{station}».", "suggC": "أضف المذيع إلى المحطة من صفحة تعديل المذيع.", "legendC": "C — مذيع مرتبط ببرنامج لكنه غير مرتبط بمحطة البرنامج",
    "typeD": "مذيع DJ مباشر في برنامج", "descD": "مذيع DJ مباشر «{presenter}» مُضاف لبرنامج «{program}» — هذا غير مدعوم.", "suggD": "احذف هذا البرنامج. مذيعو DJ المباشر لا يستخدمون جداول البرامج.", "legendD": "D — مذيع DJ مباشر مُضاف لجدول برنامج (غير مدعوم)",
    "typeE": "مذيع محطة واحدة على أكثر من محطة", "descE": "المذيع «{presenter}» (SINGLE_STATION) مرتبط بـ {count} محطات.", "suggE": "فصل المذيع عن المحطات الزائدة أو تغيير نوع الحساب إلى MULTI_STATION.", "legendE": "E — مذيع محطة واحدة مرتبط بأكثر من محطة",
    "typeF": "برنامج نشط بلا جدول", "descF": "البرنامج «{program}» على «{station}» نشط لكن لا توجد قواعد جدول زمني.", "suggF": "أضف قواعد جدول من صفحة تعديل البرنامج.", "legendF": "F — برنامج نشط بلا قواعد جدول زمني",
    "typeG": "برنامج نشط على محطة معطّلة", "descG": "البرنامج «{program}» نشط لكن محطته «{station}» معطّلة.", "suggG": "عطّل البرنامج أو أعِد تفعيل المحطة.", "legendG": "G — برنامج نشط على محطة معطّلة",
    "admin": "الإدارة", "schedule": "الجدول", "audit": "تدقيق الجداول"
  },
  "en.json": {
    "title": "Schedule Audit - Admin", "titleMain": "Schedule & Settings Audit", "subtitle": "Comprehensive check for overlaps and errors — Read-only, no data is modified.", "back": "Back →", "all": "All", "errors": "⛔ Errors", "warnings": "⚠️ Warnings", "stationLabel": "Station:", "issueType": "Issue Type:", "clearFilters": "✕ Clear Filters ({count} results)", "criticalErrors": "Critical Errors", "warningsCount": "Warnings", "activePrograms": "Total Active Programs", "noIssues": "No issues detected", "noIssuesDesc": "All schedules, presenters, and stations look healthy.", "legendTitle": "Checks performed in this report:",
    "typeA": "Schedule overlap on the same station", "descA": "\"{titleA}\" and \"{titleB}\" on \"{station}\" ({startA}–{endA} ↔ {startB}–{endB})", "suggA": "Modify the times of one program to remove the overlap.", "legendA": "A — Program times overlap on the same station",
    "typeB": "Same presenter overlap (two stations)", "descB": "Presenter \"{presenter}\" is scheduled for two programs simultaneously across different stations.", "suggB": "A presenter cannot broadcast on two stations at the same time.", "legendB": "B — Same presenter scheduled in two programs at once",
    "typeC": "Presenter not linked to program's station", "descC": "Program \"{program}\" is linked to a presenter not added to station \"{station}\".", "suggC": "Add the presenter to the station from the presenter edit page.", "legendC": "C — Presenter linked to program but not to the station",
    "typeD": "Live DJ in a program", "descD": "Live DJ \"{presenter}\" is added to program \"{program}\" — this is unsupported.", "suggD": "Delete this program. Live DJs do not use program schedules.", "legendD": "D — Live DJ added to a program schedule (unsupported)",
    "typeE": "Single-station presenter on multiple stations", "descE": "Presenter \"{presenter}\" (SINGLE_STATION) is linked to {count} stations.", "suggE": "Unlink the presenter from extra stations or change account type to MULTI_STATION.", "legendE": "E — Single-station presenter linked to multiple stations",
    "typeF": "Active program with no schedule", "descF": "Program \"{program}\" on \"{station}\" is active but has no schedule rules.", "suggF": "Add schedule rules from the program edit page.", "legendF": "F — Active program with no schedule rules",
    "typeG": "Active program on disabled station", "descG": "Program \"{program}\" is active but its station \"{station}\" is disabled.", "suggG": "Disable the program or re-enable the station.", "legendG": "G — Active program on a disabled station",
    "admin": "Admin", "schedule": "Schedule", "audit": "Schedule Audit"
  },
  "de.json": {
    "title": "Zeitplanprüfung - Admin", "titleMain": "Zeitplan & Einstellungen Prüfung", "subtitle": "Umfassende Prüfung auf Überschneidungen und Fehler — Schreibgeschützt, keine Daten werden geändert.", "back": "Zurück →", "all": "Alle", "errors": "⛔ Fehler", "warnings": "⚠️ Warnungen", "stationLabel": "Sender:", "issueType": "Problemtyp:", "clearFilters": "✕ Filter löschen ({count} Ergebnisse)", "criticalErrors": "Kritische Fehler", "warningsCount": "Warnungen", "activePrograms": "Aktive Programme", "noIssues": "Keine Probleme erkannt", "noIssuesDesc": "Alle Zeitpläne, Moderatoren und Sender sehen gut aus.", "legendTitle": "In diesem Bericht durchgeführte Prüfungen:",
    "typeA": "Zeitplanüberschneidung beim selben Sender", "descA": "\"{titleA}\" und \"{titleB}\" auf \"{station}\" ({startA}–{endA} ↔ {startB}–{endB})", "suggA": "Ändern Sie die Zeiten eines Programms, um die Überschneidung zu entfernen.", "legendA": "A — Programmzeiten überschneiden sich beim selben Sender",
    "typeB": "Überschneidung desselben Moderators (zwei Sender)", "descB": "Moderator \"{presenter}\" ist für zwei Programme gleichzeitig auf verschiedenen Sendern eingeplant.", "suggB": "Ein Moderator kann nicht gleichzeitig auf zwei Sendern senden.", "legendB": "B — Derselbe Moderator ist in zwei Programmen gleichzeitig eingeplant",
    "typeC": "Moderator nicht mit dem Sender des Programms verknüpft", "descC": "Programm \"{program}\" ist mit einem Moderator verknüpft, der nicht zum Sender \"{station}\" hinzugefügt wurde.", "suggC": "Fügen Sie den Moderator auf der Bearbeitungsseite für Moderatoren zum Sender hinzu.", "legendC": "C — Moderator mit Programm, aber nicht mit dem Sender verknüpft",
    "typeD": "Live-DJ in einem Programm", "descD": "Live-DJ \"{presenter}\" ist dem Programm \"{program}\" hinzugefügt — dies wird nicht unterstützt.", "suggD": "Löschen Sie dieses Programm. Live-DJs verwenden keine Programmzeitpläne.", "legendD": "D — Live-DJ zu einem Programmzeitplan hinzugefügt (nicht unterstützt)",
    "typeE": "Einzel-Sender-Moderator auf mehreren Sendern", "descE": "Moderator \"{presenter}\" (SINGLE_STATION) ist mit {count} Sendern verknüpft.", "suggE": "Trennen Sie den Moderator von zusätzlichen Sendern oder ändern Sie den Kontotyp auf MULTI_STATION.", "legendE": "E — Einzel-Sender-Moderator mit mehreren Sendern verknüpft",
    "typeF": "Aktives Programm ohne Zeitplan", "descF": "Programm \"{program}\" auf \"{station}\" ist aktiv, hat aber keine Zeitplanregeln.", "suggF": "Fügen Sie Zeitplanregeln auf der Bearbeitungsseite für Programme hinzu.", "legendF": "F — Aktives Programm ohne Zeitplanregeln",
    "typeG": "Aktives Programm auf deaktiviertem Sender", "descG": "Programm \"{program}\" ist aktiv, aber der Sender \"{station}\" ist deaktiviert.", "suggG": "Deaktivieren Sie das Programm oder aktivieren Sie den Sender wieder.", "legendG": "G — Aktives Programm auf einem deaktivierten Sender",
    "admin": "Admin", "schedule": "Zeitplan", "audit": "Zeitplanprüfung"
  },
  "es.json": {
    "title": "Auditoría de Horario - Admin", "titleMain": "Auditoría de Horario y Configuración", "subtitle": "Comprobación exhaustiva de solapamientos y errores — Solo lectura, no se modifican datos.", "back": "Volver →", "all": "Todos", "errors": "⛔ Errores", "warnings": "⚠️ Advertencias", "stationLabel": "Estación:", "issueType": "Tipo de Problema:", "clearFilters": "✕ Borrar Filtros ({count} resultados)", "criticalErrors": "Errores Críticos", "warningsCount": "Advertencias", "activePrograms": "Programas Activos", "noIssues": "No se detectaron problemas", "noIssuesDesc": "Todos los horarios, presentadores y estaciones se ven bien.", "legendTitle": "Comprobaciones realizadas en este informe:",
    "typeA": "Solapamiento de horario en la misma estación", "descA": "\"{titleA}\" y \"{titleB}\" en \"{station}\" ({startA}–{endA} ↔ {startB}–{endB})", "suggA": "Modifique los horarios de un programa para eliminar el solapamiento.", "legendA": "A — Los horarios de los programas se solapan en la misma estación",
    "typeB": "Solapamiento del mismo presentador (dos estaciones)", "descB": "El presentador \"{presenter}\" está programado para dos programas simultáneamente en diferentes estaciones.", "suggB": "Un presentador no puede transmitir en dos estaciones al mismo tiempo.", "legendB": "B — El mismo presentador programado en dos programas a la vez",
    "typeC": "Presentador no vinculado a la estación del programa", "descC": "El programa \"{program}\" está vinculado a un presentador no agregado a la estación \"{station}\".", "suggC": "Agregue el presentador a la estación desde la página de edición del presentador.", "legendC": "C — Presentador vinculado al programa pero no a la estación",
    "typeD": "DJ en vivo en un programa", "descD": "El DJ en vivo \"{presenter}\" se agregó al programa \"{program}\" — esto no es compatible.", "suggD": "Elimine este programa. Los DJ en vivo no utilizan horarios de programas.", "legendD": "D — DJ en vivo agregado a un horario de programa (no compatible)",
    "typeE": "Presentador de una sola estación en varias estaciones", "descE": "El presentador \"{presenter}\" (SINGLE_STATION) está vinculado a {count} estaciones.", "suggE": "Desvincule al presentador de las estaciones adicionales o cambie el tipo de cuenta a MULTI_STATION.", "legendE": "E — Presentador de una sola estación vinculado a múltiples estaciones",
    "typeF": "Programa activo sin horario", "descF": "El programa \"{program}\" en \"{station}\" está activo pero no tiene reglas de horario.", "suggF": "Agregue reglas de horario desde la página de edición del programa.", "legendF": "F — Programa activo sin reglas de horario",
    "typeG": "Programa activo en estación desactivada", "descG": "El programa \"{program}\" está activo pero su estación \"{station}\" está desactivada.", "suggG": "Desactive el programa o vuelva a activar la estación.", "legendG": "G — Programa activo en una estación desactivada",
    "admin": "Admin", "schedule": "Horario", "audit": "Auditoría de Horario"
  },
  "fr.json": {
    "title": "Audit du Programme - Admin", "titleMain": "Audit du Programme & Paramètres", "subtitle": "Vérification complète des chevauchements et erreurs — Lecture seule, aucune donnée modifiée.", "back": "Retour →", "all": "Tout", "errors": "⛔ Erreurs", "warnings": "⚠️ Avertissements", "stationLabel": "Station:", "issueType": "Type de Problème:", "clearFilters": "✕ Effacer les Filtres ({count} résultats)", "criticalErrors": "Erreurs Critiques", "warningsCount": "Avertissements", "activePrograms": "Programmes Actifs", "noIssues": "Aucun problème détecté", "noIssuesDesc": "Tous les programmes, présentateurs et stations semblent corrects.", "legendTitle": "Vérifications effectuées dans ce rapport :",
    "typeA": "Chevauchement de programme sur la même station", "descA": "\"{titleA}\" et \"{titleB}\" sur \"{station}\" ({startA}–{endA} ↔ {startB}–{endB})", "suggA": "Modifiez les horaires d'un programme pour supprimer le chevauchement.", "legendA": "A — Les horaires des programmes se chevauchent sur la même station",
    "typeB": "Chevauchement du même présentateur (deux stations)", "descB": "Le présentateur \"{presenter}\" est programmé pour deux programmes simultanément sur des stations différentes.", "suggB": "Un présentateur ne peut pas diffuser sur deux stations en même temps.", "legendB": "B — Même présentateur programmé dans deux programmes à la fois",
    "typeC": "Présentateur non lié à la station du programme", "descC": "Le programme \"{program}\" est lié à un présentateur non ajouté à la station \"{station}\".", "suggC": "Ajoutez le présentateur à la station depuis la page d'édition du présentateur.", "legendC": "C — Présentateur lié au programme mais pas à la station",
    "typeD": "DJ en direct dans un programme", "descD": "Le DJ en direct \"{presenter}\" est ajouté au programme \"{program}\" — ceci n'est pas pris en charge.", "suggD": "Supprimez ce programme. Les DJ en direct n'utilisent pas les programmes.", "legendD": "D — DJ en direct ajouté à un programme (non pris en charge)",
    "typeE": "Présentateur mono-station sur plusieurs stations", "descE": "Le présentateur \"{presenter}\" (SINGLE_STATION) est lié à {count} stations.", "suggE": "Dissociez le présentateur des stations supplémentaires ou changez le type de compte en MULTI_STATION.", "legendE": "E — Présentateur mono-station lié à plusieurs stations",
    "typeF": "Programme actif sans horaire", "descF": "Le programme \"{program}\" sur \"{station}\" est actif mais n'a pas de règles d'horaire.", "suggF": "Ajoutez des règles d'horaire depuis la page d'édition du programme.", "legendF": "F — Programme actif sans règles d'horaire",
    "typeG": "Programme actif sur station désactivée", "descG": "Le programme \"{program}\" est actif mais sa station \"{station}\" est désactivée.", "suggG": "Désactivez le programme ou réactivez la station.", "legendG": "G — Programme actif sur une station désactivée",
    "admin": "Admin", "schedule": "Programme", "audit": "Audit du Programme"
  },
  "pt.json": {
    "title": "Auditoria de Horário - Admin", "titleMain": "Auditoria de Horário e Configurações", "subtitle": "Verificação abrangente de sobreposições e erros — Somente leitura, nenhum dado é modificado.", "back": "Voltar →", "all": "Todos", "errors": "⛔ Erros", "warnings": "⚠️ Avisos", "stationLabel": "Estação:", "issueType": "Tipo de Problema:", "clearFilters": "✕ Limpar Filtros ({count} resultados)", "criticalErrors": "Erros Críticos", "warningsCount": "Avisos", "activePrograms": "Programas Ativos", "noIssues": "Nenhum problema detectado", "noIssuesDesc": "Todos os horários, apresentadores e estações parecem bem.", "legendTitle": "Verificações realizadas neste relatório:",
    "typeA": "Sobreposição de horário na mesma estação", "descA": "\"{titleA}\" e \"{titleB}\" na \"{station}\" ({startA}–{endA} ↔ {startB}–{endB})", "suggA": "Modifique os horários de um programa para remover a sobreposição.", "legendA": "A — Horários dos programas se sobrepõem na mesma estação",
    "typeB": "Sobreposição do mesmo apresentador (duas estações)", "descB": "O apresentador \"{presenter}\" está agendado para dois programas simultaneamente em estações diferentes.", "suggB": "Um apresentador não pode transmitir em duas estações ao mesmo tempo.", "legendB": "B — Mesmo apresentador agendado em dois programas de uma vez",
    "typeC": "Apresentador não vinculado à estação do programa", "descC": "O programa \"{program}\" está vinculado a um apresentador não adicionado à estação \"{station}\".", "suggC": "Adicione o apresentador à estação na página de edição do apresentador.", "legendC": "C — Apresentador vinculado ao programa, mas não à estação",
    "typeD": "DJ ao vivo em um programa", "descD": "DJ ao vivo \"{presenter}\" adicionado ao programa \"{program}\" — isso não é suportado.", "suggD": "Exclua este programa. DJs ao vivo não usam horários de programas.", "legendD": "D — DJ ao vivo adicionado a um horário de programa (não suportado)",
    "typeE": "Apresentador de estação única em várias estações", "descE": "O apresentador \"{presenter}\" (SINGLE_STATION) está vinculado a {count} estações.", "suggE": "Desvincule o apresentador de estações extras ou altere o tipo de conta para MULTI_STATION.", "legendE": "E — Apresentador de estação única vinculado a várias estações",
    "typeF": "Programa ativo sem horário", "descF": "O programa \"{program}\" na \"{station}\" está ativo, mas não tem regras de horário.", "suggF": "Adicione regras de horário na página de edição do programa.", "legendF": "F — Programa ativo sem regras de horário",
    "typeG": "Programa ativo na estação desativada", "descG": "O programa \"{program}\" está ativo, mas sua estação \"{station}\" está desativada.", "suggG": "Desative o programa ou reative a estação.", "legendG": "G — Programa ativo em uma estação desativada",
    "admin": "Admin", "schedule": "Horário", "audit": "Auditoria de Horário"
  },
  "tr.json": {
    "title": "Program Denetimi - Yönetici", "titleMain": "Program ve Ayarlar Denetimi", "subtitle": "Çakışmalar ve hatalar için kapsamlı kontrol — Salt okunur, hiçbir veri değiştirilmez.", "back": "Geri →", "all": "Tümü", "errors": "⛔ Hatalar", "warnings": "⚠️ Uyarılar", "stationLabel": "İstasyon:", "issueType": "Sorun Türü:", "clearFilters": "✕ Filtreleri Temizle ({count} sonuç)", "criticalErrors": "Kritik Hatalar", "warningsCount": "Uyarılar", "activePrograms": "Aktif Programlar", "noIssues": "Sorun tespit edilmedi", "noIssuesDesc": "Tüm programlar, sunucular ve istasyonlar iyi görünüyor.", "legendTitle": "Bu raporda gerçekleştirilen kontroller:",
    "typeA": "Aynı istasyonda program çakışması", "descA": "\"{titleA}\" ve \"{titleB}\" \"{station}\" üzerinde ({startA}–{endA} ↔ {startB}–{endB})", "suggA": "Çakışmayı gidermek için bir programın saatlerini değiştirin.", "legendA": "A — Program saatleri aynı istasyonda çakışıyor",
    "typeB": "Aynı sunucu çakışması (iki istasyon)", "descB": "Sunucu \"{presenter}\" aynı anda farklı istasyonlarda iki program için planlanmış.", "suggB": "Bir sunucu aynı anda iki istasyonda yayın yapamaz.", "legendB": "B — Aynı sunucu aynı anda iki programda planlanmış",
    "typeC": "Sunucu programın istasyonuna bağlı değil", "descC": "\"{program}\" programı, \"{station}\" istasyonuna eklenmemiş bir sunucuya bağlı.", "suggC": "Sunucu düzenleme sayfasından sunucuyu istasyona ekleyin.", "legendC": "C — Sunucu programa bağlı ancak istasyona bağlı değil",
    "typeD": "Bir programda Canlı DJ", "descD": "Canlı DJ \"{presenter}\", \"{program}\" programına eklendi — bu desteklenmiyor.", "suggD": "Bu programı silin. Canlı DJ'ler program takvimlerini kullanmazlar.", "legendD": "D — Canlı DJ bir program takvimine eklendi (desteklenmiyor)",
    "typeE": "Birden fazla istasyonda tek istasyonlu sunucu", "descE": "Sunucu \"{presenter}\" (SINGLE_STATION) {count} istasyona bağlı.", "suggE": "Sunucunun bağlantısını ekstra istasyonlardan kesin veya hesap türünü MULTI_STATION olarak değiştirin.", "legendE": "E — Tek istasyonlu sunucu birden fazla istasyona bağlı",
    "typeF": "Programı olmayan aktif program", "descF": "\"{station}\" üzerindeki \"{program}\" programı aktif ancak program kuralı yok.", "suggF": "Program düzenleme sayfasından program kuralları ekleyin.", "legendF": "F — Program kuralı olmayan aktif program",
    "typeG": "Devre dışı bırakılmış istasyonda aktif program", "descG": "\"{program}\" programı aktif ancak istasyonu \"{station}\" devre dışı.", "suggG": "Programı devre dışı bırakın veya istasyonu yeniden etkinleştirin.", "legendG": "G — Devre dışı bırakılmış bir istasyonda aktif program",
    "admin": "Yönetici", "schedule": "Program", "audit": "Program Denetimi"
  }
}


for filename, trans in langs.items():
    path = f"frontend/messages/{filename}"
    if not os.path.exists(path): continue
    with open(path, 'r', encoding='utf-8') as f: data = json.load(f)
    if "admin" not in data: data["admin"] = {}
    if "schedule" not in data["admin"]: data["admin"]["schedule"] = {}
    if "auditPage" not in data["admin"]["schedule"]: data["admin"]["schedule"]["auditPage"] = {}
    
    for k, v in trans.items():
        data["admin"]["schedule"]["auditPage"][k] = v
        
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Proper translations injected.")
