steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/egonair-stream-prod/egonair/backend-audio:latest'
      - '.'
  
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/egonair-stream-prod/egonair/backend-audio:latest'

images:
  - 'europe-west1-docker.pkg.dev/egonair-stream-prod/egonair/backend-audio:latest'
