version: "3.8"

services:
  shoutcast:
    image: infiniteproject/shoutcast
    container_name: shoutcast-server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PASSWORD=testing
      - ADMINPASSWORD=testing_admin
